# Generated by Django 4.0.3 on 2022-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_gettextfromfield_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gettextfromfield',
            old_name='textFileld',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='gettextfromfield',
            name='classPredicted',
        ),
        migrations.RemoveField(
            model_name='gettextfromfield',
            name='createdAt',
        ),
    ]
