# Generated by Django 4.0.3 on 2022-05-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_text_postcomment_comment_postcomment_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='comment',
        ),
    ]
